server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/etca
    username: root
    password: 1234

logging:
  level:
    org:
      # springframework:
        # web: ERROR
        # security: ERROR
      hibernate: ERROR