server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/etca
    username: root
    password: 1234

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: DEBUG